const categoryQuestionList = [{
	"category": 48,
	"rule": 1,
	"name": "选择题",
	"subjectId": 17,
	"questionList": []
}, {
	"category": 49,
	"rule": 3,
	"name": "填空题",
	"subjectId": 17,
	"questionList": [{
		"id": 7464105,
		"contentPng": null,
		"content": "写出图中字母所代表的地理事物的名称。\nA以____%为主的耕地；B以____%为主的耕地。\n",
		"answerPng": null,
		"answer": "略\n",
		"analysisPng": null,
		"analysis": "【解析】略\n",
		"category": 49,
		"subjectId": 17,
		"gradeId": 11,
		"creatorId": 21,
		"createTime": 1736150521000,
		"updatorId": null,
		"updateTime": 1736240289000,
		"yearId": 2025,
		"schoolId": 154,
		"difficulty": 0.04,
		"type": 9,
		"jobId": null,
		"rangeId": null,
		"isSetParam": null,
		"code": null,
		"parentId": null,
		"markCode": null,
		"questionNum": null,
		"topicCode": null,
		"knowName": "地球的模型——地球仪",
		"knowIds": "7963",
		"compIds": null,
		"compName": null,
		"cognIds": null,
		"cognName": null,
		"abilityIds": null,
		"abilityName": null,
		"optionList": [],
		"options": null,
		"optionType": null,
		"questionData": null,
		"penType": null,
		"pointData": null,
		"serialCode": null,
		"questionId": null,
		"difficultyInt": null,
		"diffName": null,
		"collect": null,
		"notes": null,
		"massage": null,
		"massageIds": null,
		"isErro": null,
		"score": 42,
		"fullMark": null,
		"tempId": 45,
		"taskId": null,
		"paperId": null,
		"studentAnswer": null,
		"answerId": null,
		"isTrue": null,
		"isObjective": null,
		"answerTraceId": null,
		"dataId": 439924,
		"dataContent": "读“中国主要土地利用类型分布图”，完成下列各题。\n[myImgCur]\n",
		"dataAnalysis": null,
		"dataContentPng": "2501061602ce7a66bd17.png",
		"dataAnalysisPng": null,
		"rule": null,
		"categoryName": null,
		"cx1": null,
		"cx2": null,
		"cy1": null,
		"cy2": null,
		"pageId": null,
		"pageSerial": null,
		"questionTypeStr": null,
		"questionScore": null,
		"materialQuestionList": [{
			"id": 7464105,
			"questionId": null,
			"content": "写出图中字母所代表的地理事物的名称。\nA以____%为主的耕地；B以____%为主的耕地。\n",
			"contentPng": null,
			"answer": "略\n",
			"answerPng": null,
			"analysis": "【解析】略\n",
			"analysisPng": null,
			"difficulty": 0.04,
			"knowIds": "7963",
			"knowName": "地球的模型——地球仪",
			"optionList": [],
			"options": null,
			"dataId": null,
			"userId": null,
			"paperId": null,
			"paperName": null,
			"createTime": null,
			"dataContent": null,
			"dataContentPng": null,
			"questionNum": "1",
			"serialCode": null,
			"category": 49,
			"tempId": 45,
			"parentId": null,
			"markCode": null,
			"score": 3,
			"materialQuestionList": null,
			"categoryName": "填空题",
			"abilityName": null,
			"cognName": null,
			"compName": null,
			"rule": 3,
			"isObjective": 1,
			"subjectId": 17,
			"titleScore": null,
			"serialNumber": 1
		}, {
			"id": 7464106,
			"questionId": null,
			"content": "图中 A、B所代表的土地利用类型主要分布在我国东部季风区，东部季风区从\n干湿状况看，大部分属于____%区和____%区；从地形类型看，主要有____%、____%和低山丘陵。\n",
			"contentPng": null,
			"answer": "略\n",
			"answerPng": null,
			"analysis": "【解析】略\n",
			"analysisPng": null,
			"difficulty": 0.01,
			"knowIds": "7963",
			"knowName": "地球的模型——地球仪",
			"optionList": [],
			"options": null,
			"dataId": null,
			"userId": null,
			"paperId": null,
			"paperName": null,
			"createTime": null,
			"dataContent": null,
			"dataContentPng": null,
			"questionNum": "2",
			"serialCode": null,
			"category": 49,
			"tempId": 46,
			"parentId": null,
			"markCode": null,
			"score": 3,
			"materialQuestionList": null,
			"categoryName": "填空题",
			"abilityName": null,
			"cognName": null,
			"compName": null,
			"rule": 3,
			"isObjective": 1,
			"subjectId": 17,
			"titleScore": null,
			"serialNumber": 2
		}, {
			"id": 7464107,
			"questionId": null,
			"content": "我国北部、西部内陆地区，土地利用类型以____%为主；林地主要分布在我国的____%、____%和南方(或东南)的山地丘陵区。\n",
			"contentPng": null,
			"answer": "略\n",
			"answerPng": null,
			"analysis": "【解析】略\n",
			"analysisPng": null,
			"difficulty": 0.13,
			"knowIds": "7963",
			"knowName": "地球的模型——地球仪",
			"optionList": [],
			"options": null,
			"dataId": null,
			"userId": null,
			"paperId": null,
			"paperName": null,
			"createTime": null,
			"dataContent": null,
			"dataContentPng": null,
			"questionNum": "3",
			"serialCode": null,
			"category": 49,
			"tempId": 47,
			"parentId": null,
			"markCode": null,
			"score": 3,
			"materialQuestionList": null,
			"categoryName": "填空题",
			"abilityName": null,
			"cognName": null,
			"compName": null,
			"rule": 3,
			"isObjective": 1,
			"subjectId": 17,
			"titleScore": null,
			"serialNumber": 3
		}, {
			"id": 7464108,
			"questionId": null,
			"content": "【综合思维】我国土地在开发利用过程中存在着诸多问题。下列漫画反映出\n土地资源受到了保护的是 ( )\n[myImgCur]\n",
			"contentPng": "2501061602541514e217.png",
			"answer": "略\n",
			"answerPng": null,
			"analysis": "【解析】略\n",
			"analysisPng": null,
			"difficulty": 0.17,
			"knowIds": "7963",
			"knowName": "地球的模型——地球仪",
			"optionList": [],
			"options": null,
			"dataId": null,
			"userId": null,
			"paperId": null,
			"paperName": null,
			"createTime": null,
			"dataContent": null,
			"dataContentPng": null,
			"questionNum": "4",
			"serialCode": null,
			"category": 49,
			"tempId": 48,
			"parentId": null,
			"markCode": null,
			"score": 3,
			"materialQuestionList": null,
			"categoryName": "填空题",
			"abilityName": null,
			"cognName": null,
			"compName": null,
			"rule": 3,
			"isObjective": 1,
			"subjectId": 17,
			"titleScore": null,
			"serialNumber": 4
		}, {
			"id": 7464109,
			"questionId": null,
			"content": "【人地协调观】由于过度开垦、过度放牧、不合理利用水资源，内蒙古牧区出现了土地沙化、沙尘暴频发等生态环境恶化现象。要想重现“风吹草低见牛羊”的景象应该采取哪些措施?\n",
			"contentPng": null,
			"answer": "略\n",
			"answerPng": null,
			"analysis": "【解析】略\n",
			"analysisPng": null,
			"difficulty": 0.18,
			"knowIds": "7963",
			"knowName": "地球的模型——地球仪",
			"optionList": [],
			"options": null,
			"dataId": null,
			"userId": null,
			"paperId": null,
			"paperName": null,
			"createTime": null,
			"dataContent": null,
			"dataContentPng": null,
			"questionNum": "5",
			"serialCode": null,
			"category": 49,
			"tempId": 49,
			"parentId": null,
			"markCode": null,
			"score": 3,
			"materialQuestionList": null,
			"categoryName": "填空题",
			"abilityName": null,
			"cognName": null,
			"compName": null,
			"rule": 3,
			"isObjective": 1,
			"subjectId": 17,
			"titleScore": null,
			"serialNumber": 5
		}, {
			"id": 7464110,
			"questionId": null,
			"content": "写出图中字母所代表的地理事物的名称。\nA以____",
			"contentPng": null,
			"answer": null,
			"answerPng": null,
			"analysis": "【解析】略\n",
			"analysisPng": null,
			"difficulty": 0.04,
			"knowIds": "7963",
			"knowName": "地球的模型——地球仪",
			"optionList": [],
			"options": null,
			"dataId": null,
			"userId": null,
			"paperId": null,
			"paperName": null,
			"createTime": null,
			"dataContent": null,
			"dataContentPng": null,
			"questionNum": "1",
			"serialCode": null,
			"category": 49,
			"tempId": 50,
			"parentId": 7464105,
			"markCode": null,
			"score": 3,
			"materialQuestionList": null,
			"categoryName": "填空题",
			"abilityName": null,
			"cognName": null,
			"compName": null,
			"rule": 3,
			"isObjective": 1,
			"subjectId": 17,
			"titleScore": null,
			"serialNumber": 6
		}, {
			"id": 7464111,
			"questionId": null,
			"content": "为主的耕地；B以____",
			"contentPng": null,
			"answer": null,
			"answerPng": null,
			"analysis": "【解析】略\n",
			"analysisPng": null,
			"difficulty": 0.04,
			"knowIds": "7963",
			"knowName": "地球的模型——地球仪",
			"optionList": [],
			"options": null,
			"dataId": null,
			"userId": null,
			"paperId": null,
			"paperName": null,
			"createTime": null,
			"dataContent": null,
			"dataContentPng": null,
			"questionNum": "1",
			"serialCode": null,
			"category": 49,
			"tempId": 51,
			"parentId": 7464105,
			"markCode": null,
			"score": 3,
			"materialQuestionList": null,
			"categoryName": "填空题",
			"abilityName": null,
			"cognName": null,
			"compName": null,
			"rule": 3,
			"isObjective": 1,
			"subjectId": 17,
			"titleScore": null,
			"serialNumber": 7
		}, {
			"id": 7464112,
			"questionId": null,
			"content": "图中 A、B所代表的土地利用类型主要分布在我国东部季风区，东部季风区从\n干湿状况看，大部分属于____",
			"contentPng": null,
			"answer": null,
			"answerPng": null,
			"analysis": "【解析】略\n",
			"analysisPng": null,
			"difficulty": 0.01,
			"knowIds": "7963",
			"knowName": "地球的模型——地球仪",
			"optionList": [],
			"options": null,
			"dataId": null,
			"userId": null,
			"paperId": null,
			"paperName": null,
			"createTime": null,
			"dataContent": null,
			"dataContentPng": null,
			"questionNum": "2",
			"serialCode": null,
			"category": 49,
			"tempId": 52,
			"parentId": 7464106,
			"markCode": null,
			"score": 3,
			"materialQuestionList": null,
			"categoryName": "填空题",
			"abilityName": null,
			"cognName": null,
			"compName": null,
			"rule": 3,
			"isObjective": 1,
			"subjectId": 17,
			"titleScore": null,
			"serialNumber": 8
		}, {
			"id": 7464113,
			"questionId": null,
			"content": "区和____",
			"contentPng": null,
			"answer": null,
			"answerPng": null,
			"analysis": "【解析】略\n",
			"analysisPng": null,
			"difficulty": 0.01,
			"knowIds": "7963",
			"knowName": "地球的模型——地球仪",
			"optionList": [],
			"options": null,
			"dataId": null,
			"userId": null,
			"paperId": null,
			"paperName": null,
			"createTime": null,
			"dataContent": null,
			"dataContentPng": null,
			"questionNum": "2",
			"serialCode": null,
			"category": 49,
			"tempId": 53,
			"parentId": 7464106,
			"markCode": null,
			"score": 3,
			"materialQuestionList": null,
			"categoryName": "填空题",
			"abilityName": null,
			"cognName": null,
			"compName": null,
			"rule": 3,
			"isObjective": 1,
			"subjectId": 17,
			"titleScore": null,
			"serialNumber": 9
		}, {
			"id": 7464114,
			"questionId": null,
			"content": "区；从地形类型看，主要有____",
			"contentPng": null,
			"answer": null,
			"answerPng": null,
			"analysis": "【解析】略\n",
			"analysisPng": null,
			"difficulty": 0.01,
			"knowIds": "7963",
			"knowName": "地球的模型——地球仪",
			"optionList": [],
			"options": null,
			"dataId": null,
			"userId": null,
			"paperId": null,
			"paperName": null,
			"createTime": null,
			"dataContent": null,
			"dataContentPng": null,
			"questionNum": "2",
			"serialCode": null,
			"category": 49,
			"tempId": 54,
			"parentId": 7464106,
			"markCode": null,
			"score": 3,
			"materialQuestionList": null,
			"categoryName": "填空题",
			"abilityName": null,
			"cognName": null,
			"compName": null,
			"rule": 3,
			"isObjective": 1,
			"subjectId": 17,
			"titleScore": null,
			"serialNumber": 10
		}, {
			"id": 7464115,
			"questionId": null,
			"content": "、____",
			"contentPng": null,
			"answer": null,
			"answerPng": null,
			"analysis": "【解析】略\n",
			"analysisPng": null,
			"difficulty": 0.01,
			"knowIds": "7963",
			"knowName": "地球的模型——地球仪",
			"optionList": [],
			"options": null,
			"dataId": null,
			"userId": null,
			"paperId": null,
			"paperName": null,
			"createTime": null,
			"dataContent": null,
			"dataContentPng": null,
			"questionNum": "2",
			"serialCode": null,
			"category": 49,
			"tempId": 55,
			"parentId": 7464106,
			"markCode": null,
			"score": 3,
			"materialQuestionList": null,
			"categoryName": "填空题",
			"abilityName": null,
			"cognName": null,
			"compName": null,
			"rule": 3,
			"isObjective": 1,
			"subjectId": 17,
			"titleScore": null,
			"serialNumber": 11
		}, {
			"id": 7464116,
			"questionId": null,
			"content": "我国北部、西部内陆地区，土地利用类型以____",
			"contentPng": null,
			"answer": null,
			"answerPng": null,
			"analysis": "【解析】略\n",
			"analysisPng": null,
			"difficulty": 0.13,
			"knowIds": "7963",
			"knowName": "地球的模型——地球仪",
			"optionList": [],
			"options": null,
			"dataId": null,
			"userId": null,
			"paperId": null,
			"paperName": null,
			"createTime": null,
			"dataContent": null,
			"dataContentPng": null,
			"questionNum": "3",
			"serialCode": null,
			"category": 49,
			"tempId": 56,
			"parentId": 7464107,
			"markCode": null,
			"score": 3,
			"materialQuestionList": null,
			"categoryName": "填空题",
			"abilityName": null,
			"cognName": null,
			"compName": null,
			"rule": 3,
			"isObjective": 1,
			"subjectId": 17,
			"titleScore": null,
			"serialNumber": 12
		}, {
			"id": 7464117,
			"questionId": null,
			"content": "为主；林地主要分布在我国的____",
			"contentPng": null,
			"answer": null,
			"answerPng": null,
			"analysis": "【解析】略\n",
			"analysisPng": null,
			"difficulty": 0.13,
			"knowIds": "7963",
			"knowName": "地球的模型——地球仪",
			"optionList": [],
			"options": null,
			"dataId": null,
			"userId": null,
			"paperId": null,
			"paperName": null,
			"createTime": null,
			"dataContent": null,
			"dataContentPng": null,
			"questionNum": "3",
			"serialCode": null,
			"category": 49,
			"tempId": 57,
			"parentId": 7464107,
			"markCode": null,
			"score": 3,
			"materialQuestionList": null,
			"categoryName": "填空题",
			"abilityName": null,
			"cognName": null,
			"compName": null,
			"rule": 3,
			"isObjective": 1,
			"subjectId": 17,
			"titleScore": null,
			"serialNumber": 13
		}, {
			"id": 7464118,
			"questionId": null,
			"content": "、____",
			"contentPng": null,
			"answer": null,
			"answerPng": null,
			"analysis": "【解析】略\n",
			"analysisPng": null,
			"difficulty": 0.57,
			"knowIds": "7963",
			"knowName": "地球的模型——地球仪",
			"optionList": [],
			"options": null,
			"dataId": null,
			"userId": null,
			"paperId": null,
			"paperName": null,
			"createTime": null,
			"dataContent": null,
			"dataContentPng": null,
			"questionNum": "3",
			"serialCode": null,
			"category": 49,
			"tempId": 58,
			"parentId": 7464107,
			"markCode": null,
			"score": 3,
			"materialQuestionList": null,
			"categoryName": "填空题",
			"abilityName": null,
			"cognName": null,
			"compName": null,
			"rule": 3,
			"isObjective": 1,
			"subjectId": 17,
			"titleScore": null,
			"serialNumber": 14
		}],
		"questionList": null,
		"subjectName": null,
		"versionId": null,
		"versionName": null,
		"flag": null,
		"isCollect": null,
		"joinErrorBook": null,
		"joinTime": null,
		"joinType": null,
		"masterTime": null,
		"sourceName": null,
		"errorReason": null,
		"jobTypeName": null,
		"totalScore": null,
		"isCorrect": null,
		"comment": null,
		"tQuestionVideoList": null,
		"no": null,
		"scoreLevel": null,
		"revise": null,
		"ability": null,
		"excepName": null,
		"complete": null,
		"completeed": null,
		"height": null,
		"dimeName": null,
		"dimeIds": null,
		"useNumber": 0,
		"serialNumber": 14
	}]
}, {
	"category": 50,
	"rule": 4,
	"name": "连线题",
	"subjectId": 17,
	"questionList": []
}, {
	"category": 51,
	"rule": 2,
	"name": "判断题",
	"subjectId": 17,
	"questionList": []
}, {
	"category": 52,
	"rule": 4,
	"name": "解答题",
	"subjectId": 17,
	"questionList": []
}, {
	"category": 310,
	"rule": 9,
	"name": "多选题",
	"subjectId": 17,
	"questionList": []
}]

const template = {
  "success": true,
  "data": {
    "id": 96,
    "teacherId": 395165,
    "name": "地理模板I",
    "subjectId": 17,
    "subjectName": "地理",
    "paperType": "3",
    "schoolId": 155,
    "stuName": 1,
    "stuClass": 1,
    "stuNum": 1,
    "stuNameId": 1,
    "stuClassId": 2,
    "stuNumId": 3,
    "font": "仿宋",
    "wordSize": "16号",
    "composeType": "竖排",
    "alignment": "居中",
    "sealLine": "虚线显示",
    "updateTime": 1736326779000,
    "templateDetails": [
      {
        "id": 49,
        "paperTempId": 96,
        "categoryId": 48,
        "categoryName": "选择题",
        "reviewType": "1",
        "arrayType": "1",
        "isArea": "0",
        "height": "110.0",
        "scoreSet": "2",
        "smallItem": 0,
        "updateTime": 1736326779000
      },
      {
        "id": 50,
        "paperTempId": 96,
        "categoryId": 49,
        "categoryName": "填空题",
        "reviewType": "3",
        "arrayType": "1",
        "isArea": "0",
        "height": "110.0",
        "scoreSet": "2",
        "smallItem": 1,
        "updateTime": 1736326779000
      },
      {
        "id": 51,
        "paperTempId": 96,
        "categoryId": 50,
        "categoryName": "连线题",
        "reviewType": "3",
        "arrayType": "1",
        "isArea": "0",
        "height": "0.0",
        "scoreSet": "2",
        "smallItem": 0,
        "updateTime": 1736326779000
      },
      {
        "id": 52,
        "paperTempId": 96,
        "categoryId": 51,
        "categoryName": "判断题",
        "reviewType": "1",
        "arrayType": "1",
        "isArea": "0",
        "height": "110.0",
        "scoreSet": "2",
        "smallItem": 0,
        "updateTime": 1736326779000
      },
      {
        "id": 53,
        "paperTempId": 96,
        "categoryId": 52,
        "categoryName": "解答题",
        "reviewType": "2",
        "arrayType": "4",
        "isArea": "1",
        "height": "110.0",
        "scoreSet": "2",
        "smallItem": 0,
        "updateTime": 1736326779000
      },
      {
        "id": 54,
        "paperTempId": 96,
        "categoryId": 310,
        "categoryName": "多选题",
        "reviewType": "1",
        "arrayType": "1",
        "isArea": "0",
        "height": "110.0",
        "scoreSet": "2",
        "smallItem": 0,
        "updateTime": 1736326779000
      }
    ],
    "templatePageSets": [
      {
        "id": 67,
        "paperTempId": 96,
        "seqNo": 1,
        "pageSetId": "1",
        "pageSetName": "跨页时，答题区域自动分页至下一页",
        "updateTime": 1736326779000
      },
      {
        "id": 68,
        "paperTempId": 96,
        "seqNo": 2,
        "pageSetId": "2",
        "pageSetName": "跨页时，答题区域自动分割在两页",
        "updateTime": 1736326779000
      },
      {
        "id": 69,
        "paperTempId": 96,
        "seqNo": 3,
        "pageSetId": "3",
        "pageSetName": "跨页时，题目、批阅区域、答题区域自¨åé¡µè³ä¸ä¸é¡µ",
        "updateTime": 1736326779000
      }
    ]
  },
  "message": "successful",
  "errCode": 0,
  "errDetail": null
}

function organizeQuestionListByParentId(questionList) {
  const questionMap = new Map()
  questionList.forEach(question => {
    question.childrenList = []
    questionMap.set(question.id, question)
  })
  for (let i = questionList.length -1; i >= 0; i--) {
    if (questionList[i].parentId) {
      const parent = questionMap.get(questionList[i].parentId)
      if (parent) {
        const content = parent.content
        const lastIndex = content.lastIndexOf('____')
        if (lastIndex !== -1) {
          questionList[i].lastContent = content.slice(lastIndex + 4)
        }
        parent.childrenList.unshift(questionList[i])
        questionList.splice(i, 1)
      }
    }
  }
}

function organizeMaterialQuestionList(materialQuestionList) {
  if (Array.isArray(materialQuestionList) && materialQuestionList.length > 0) {
    organizeQuestionListByParentId(materialQuestionList)
    materialQuestionList.forEach(materialQuestion => {
      if (Array.isArray(materialQuestion.materialQuestionList) && materialQuestion.materialQuestionList.length > 0) {
        organizeMaterialQuestionList(materialQuestion.materialQuestionList)
      }
    })
  }
}

function organizeCategoryQuestionList(categoryQuestionList) {
  categoryQuestionList.forEach(categoryQuestion => {
    if (Array.isArray(categoryQuestion.questionList) && categoryQuestion.questionList.length > 0) {
      const questionList = categoryQuestion.questionList
      organizeQuestionListByParentId(questionList)
      questionList.forEach(question => {
        if (Array.isArray(question.materialQuestionList) && question.materialQuestionList.length > 0) {
          const materialQuestionList = question.materialQuestionList
          organizeQuestionListByParentId(materialQuestionList)
        }
      })
    }
  })
  return categoryQuestionList
}

function organizeQuestionListByChildrenList(questionList) {
  questionList.forEach(question => {
    if (Array.isArray(question.childrenList) && question.childrenList.length > 0) {
      questionList.push(...question.childrenList)
    }
    if (Array.isArray(question.materialQuestionList) && question.materialQuestionList.length > 0) {
      organizeQuestionListByChildrenList(question.materialQuestionList)
    }
  })
}

function restoreCategoryListByTemplate(categoryQuestionList, templateList) {
  const categoryMap = categoryQuestionList.reduce((acc, category) => (acc[category.name] = category, acc), {})
  templateList.forEach(template => {
    if (template.smallItem === 1) {
      const category = categoryMap[template.categoryName]
      if (category) {
        organizeQuestionListByChildrenList(category.questionList)
      }
    }
  })
  return categoryQuestionList
}

const organizedList = organizeCategoryQuestionList(categoryQuestionList)
const restoredList = restoreCategoryListByTemplate(organizedList, template.data.templateDetails)
console.log('organizedList: ', organizedList)
console.log('restoredList: ', restoredList)